
{'date': 'Sat Feb 13 2021 18:08:40.473 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    jogo()
  module <module> line 8
    cenaIlha = Cena(img = "https://i.imgur.com/5UvVC5M.png")
TypeError: 'module' object is not callable
'''},
{'date': 'Sat Feb 13 2021 18:46:10.95 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 15
    jogo()
  module <module> line 13
    okami1.vai = txtokami1.vai
NameError: name 'txtokami1' is not defined
'''},
{'date': 'Sat Feb 13 2021 19:23:50.400 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 20
    jogo()
  module <module> line 15
    waka1.entra(cenaIlha)
NameError: name 'waka1' is not defined
'''},
{'date': 'Sat Feb 13 2021 21:31:26.727 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 34
  txtrat1 = Texto(cena_gruta, "afie minha espada mas por um porem prove sue valor completando ésa missão.")
  ^
IndentationError: unexpected indent
'''},
{'date': 'Sat Feb 13 2021 21:35:15.184 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 40
  cenaIlha = Cena(img = "https://i.imgur.com/5UvVC5M.png")
  ^
IndentationError: unexpected indent
'''},
{'date': 'Sat Feb 13 2021 21:39:23.197 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 40
  cenaIlha = Cena(img = "https://i.imgur.com/5UvVC5M.png")
  ^
IndentationError: unexpected indent
'''},